### ISSUE TITLE
[Question During training of a RecurrentPPO agent, does the "lstm_states" reset at the end of each episode?

### ISSUE THREAD

**Issue by HaakonFlaaronning** [Stable-Baselines-Team/stable-baselines3-contrib#169]
### ❓ Question

Using a Farma gymnasium environment, does the lstm_states property reset each time the step() function returns "True" for "done"? Is there a way to manually reset the lstm_states during training? This may have something to do with the "episode_start" argument? ...The use of it is not perfectly clear to me after reading the docs.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues) in the repo
- [X] I have read the [documentation](https://sb3-contrib.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,

> does the lstm_states property reset each time the step() function returns "True" for "done"? 

yes, `episode_start` has a similar role to `done`, but slightly shifted: the first step (instead of the last step) of each episode will be true.

>  This may have something to do with the "episode_start" argument?

yes.

> The use of it is not perfectly clear to me after reading the docs.

Don't be afraid to look at the code in that case ;)

https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/blob/6bc8e426bf249a42b195ee2f4c132a91cbd3968d/sb3_contrib/common/recurrent/policies.py#L202-L204
