### ISSUE TITLE
Installing an earlier version of stable-baselines3-contrib (version 1.0) results in endless backtracking of some dependencies

### ISSUE THREAD

**Issue by amy12xx** [Stable-Baselines-Team/stable-baselines3-contrib#36]
Installing an earlier version of stable-baselines3-contrib (version 1.0) results in endless backtracking of some dependencies. SB3 1.0 was previously installed before running this operation.

Tried it on google colab, with GPU (but previously got this error on a linux server as well)

!pip install sb3-contrib==1.0

```bash
INFO: pip is looking at multiple versions of coverage to determine which version is compatible with other requirements. This could take a while.
Collecting coverage>=5.2.1
  Using cached coverage-5.4-cp37-cp37m-manylinux2010_x86_64.whl (242 kB)
  Using cached coverage-5.3.1-cp37-cp37m-manylinux2010_x86_64.whl (242 kB)
  Using cached coverage-5.3-cp37-cp37m-manylinux1_x86_64.whl (229 kB)
  Using cached coverage-5.2.1-cp37-cp37m-manylinux1_x86_64.whl (229 kB)
INFO: pip is looking at multiple versions of pytest-cov to determine which version is compatible with other requirements. This could take a while.
Collecting pytest-cov
  Using cached pytest_cov-2.12.0-py2.py3-none-any.whl (20 kB)
INFO: pip is looking at multiple versions of coverage[toml] to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of coverage to determine which version is compatible with other requirements. This could take a while.
  Using cached pytest_cov-2.11.1-py2.py3-none-any.whl (20 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
  Downloading pytest_cov-2.11.0-py2.py3-none-any.whl (20 kB)

```

**Comment by araffin** [comment]
Hello,

thanks for spotting this issue, this is due to SB3 contrib trying to install `stable-baselines3[docs,tests,extra]` (I removed that full dep in https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/commit/61bfdbc00a6d5e09b401e29b2190aa7a2079d8e8 so the issue is not present with sb3-contrib>=1.1.0).
The first solution is to install `!pip install stable-baselines3[docs,tests,extra]==1.0` first (takes a while though because of the backtracking).

If you want to make things faster, you can use `--use-deprecated=legacy-resolver` or `--no-deps` (if SB3 is already installed, this is the recommended way) as suggested in [stack overflow](https://stackoverflow.com/questions/65122957/resolving-new-pip-backtracking-runtime-issue).

**Comment by amy12xx** [comment]
Thanks @araffin , I can use the workaround.
